---
functional:
   - Пользователи должны иметь возможность соревноваться друг с другом в решении задач
   - Пользователи должны иметь возможность играть с ботом
   - Пользователи должны иметь возможность играть с другом по ссылке
   - Пользователи должны иметь возможность просматривать рейтинги

non-functional:
   - Сайт должен быть удобен в использовании
   - Сайт должен быть оптимизирован для быстрой работы
   - Сайт должен обеспечивать безопасность и защиту данных пользователей
   - Сайт должен иметь мобильную версию
   - Сайт нужно протестировать на совместимость с последними версиями браузеров
   - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
   - Сайт должен поддерживать интерактивное взаимодействие с пользователями
   - Сайт должен быть доступен 24/7 без существенных простоев
   - Сайт должен обеспечивать честное соревнование между пользователями
