---
functional:
   - Пользователь должен иметь возможность зарегестрироваться на сайте
   - Пользователь должен иметь возможность авторизоваться на сайте
   - Пользователь должен иметь возможность создавать игру
   - Пользователи должны иметь возможность соревноваться друг с другом в решении задач
   - Пользователи должны иметь возможность играть с ботом
   - Пользователи должны иметь возможность играть с другом по ссылке
   - Пользователи должны иметь возможность просматривать рейтинги

non-functional:
   - Сайт должен быть удобен в использовании
   - Сайт должен быть оптимизирован для быстрой работы
   - Сайт должен обеспечивать безопасность и защиту данных пользователей
   - Сайт должен иметь мобильную версию
   - Сайт должен быть совместим с последней, на момент тестирования, версией браузера Google Chrome, Firefox и Explorer 22
   - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
   - Сайт должен быть доступен 24/7 без существенных простоев
   - Сайт должен обеспечивать честное соревнование между пользователями
   - Пользователь должен иметь возможность повторно подключиться к игре при потере соединения до завершения игры
   - Пользователь должен иметь возможность оставить обратную связь об ошибках в задачах
